# Site
name: "@jeonseonghu"
title: "@jeonseonghu"
description: "Research."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
google_analytics: ''
# Comments via Utterances (GitHub Issues)
# disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  jeonseonghu:
    name: Seonghu Jeon
    display_name: Seonghu Jeon
    avatar: assets/images/seonghu_jeungsa.png
    gravatar: 
    email: 
    web: https://jeonseonghu.github.io
    twitter: 
    description: "Research."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-polyglot
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, vendor, _site, node_modules, .sass-cache, .jekyll-cache, .jekyll-metadata]

# Internationalization (jekyll-polyglot)
languages: ["ko", "en"]
default_lang: "ko"
exclude_from_localization:
  - assets
  - vendor
  - node_modules
  - _site
  - feed.xml
  - start.sh
  - docker-compose.yml
